<a href="https://colab.research.google.com/github/kebab03/2side/blob/main/manim17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!sudo apt update
!sudo apt install libcairo2-dev ffmpeg \
    texlive texlive-latex-extra texlive-fonts-extra \
    texlive-latex-recommended texlive-science \
    tipa libpango1.0-dev


Get:1 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease [3,622 B]
Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease [1,581 B]
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:5 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal InRelease
Get:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Hit:7 http://ppa.launchpad.net/cran/libgit2/ubuntu focal InRelease
Get:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages [973 kB]
Hit:9 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
Get:10 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Hit:11 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease
Hit:12 http://ppa.launchpad.net/ubuntugis/ppa/ubuntu focal InRelease
Get:13 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [

In [2]:

!pip install manim

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 530.2/530.2 kB 9.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 49.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.8/51.8 kB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 344.6/344.6 kB 25.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 369.2/369.2 kB 26.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 68.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 79.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 kB 8.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [3]:
!pip install IPython --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 796.4/796.4 kB 12.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 53.6 MB/s eta 0:00:00
  Attempting uninstall: IPython
    Found existing installation: ipython 7.34.0
    Uninstalling ipython-7.34.0:
      Successfully uninstalled ipython-7.34.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires ipython~=7.34.0, but you have ipython 8.12.0 which is incompatible.


In [4]:
!pip install manim==0.17.0


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 523.2/523.2 kB 9.2 MB/s eta 0:00:00
  Attempting uninstall: manim
    Found existing installation: manim 0.17.3
    Uninstalling manim-0.17.3:
      Successfully uninstalled manim-0.17.3


In [5]:
!pip install IPython


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [7]:
import manim

ContextualVersionConflict: ignored

In [8]:
pip list

Package                       Version
----------------------------- --------------------
absl-py                       1.4.0
alabaster                     0.7.13
albumentations                1.2.1
altair                        4.2.2
anyio                         3.6.2
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arviz                         0.15.1
astropy                       5.2.2
asttokens                     2.2.1
astunparse                    1.6.3
attrs                         22.2.0
audioread                     3.0.0
autograd                      1.5
Babel                         2.12.1
backcall                      0.2.0
beautifulsoup4                4.11.2
bleach                        6.0.0
blis                          0.7.9
blosc2                        2.0.0
bokeh                         2.4.3
branca                        0.6.0
CacheControl                  0.12.11
cached-property               1.5.2
cach

In [1]:
from manim import *

Manim Community v0.17.0

In [2]:
%%manim -qm -v WARNING SquareToCircle

class SquareToCircle(Scene):
   def construct(self):
      square = Square()
      circle = Circle()
      circle.set_fill(PINK, opacity=0.5)
      self.play(Create(square))
      self.play(Transform(square, circle))
      self.wait()

In [3]:
%%manim -ql SineFunctionWithUnitCircle
from manim import *

class SineFunctionWithUnitCircle(Scene):
    # contributed by heejin_park, https://infograph.tistory.com/230
    def construct(self):
        self.show_axis()
        self.show_circle()
        self.move_dot_and_draw_curve()
        
        self.wait()

    def show_axis(self):
        x_start = np.array([-6,0,0])
        x_end = np.array([6,0,0])

        y_start = np.array([-4,-2,0])
        y_end = np.array([-4,2,0])

        x_axis = Line(x_start, x_end)
        y_axis = Line(y_start, y_end)

        self.add(x_axis, y_axis)
        self.add_x_labels()

        self.origin_point = np.array([-4,0,0])
        self.a=Dot().move_to(np.array([2,0,0]))
        def shift_right(obj, dt):
            obj.shift(RIGHT * 4 * dt)
            print(obj.get_center())  # print the coordinate of obj

        self.a.add_updater(shift_right)
        self.curve_start = self.a.get_center()
        self.add(self.a)
        
        #np.array([3,0,0])

    def add_x_labels(self):
        x_labels = [
            MathTex("\pi"), MathTex("2 \pi"),
            MathTex("3 \pi"), MathTex("4 \pi"),
        ]

        for i in range(len(x_labels)):
            x_labels[i].next_to(np.array([-1 + 2*i, 0, 0]), DOWN)
            self.add(x_labels[i])

    def show_circle(self):
        circle = Circle(radius=1)
        circle.move_to(self.origin_point)
        self.add(circle)
        self.circle = circle

    def move_dot_and_draw_curve(self):
        orbit = self.circle
        origin_point = self.origin_point

        dot = Dot(radius=0.06, color=YELLOW)
        dot.move_to(orbit.point_from_proportion(0))
        self.t_offset = 0
        rate = 0.25

        def go_around_circle(mob, dt):
            self.t_offset += (dt * rate)
            # print(self.t_offset)
            mob.move_to(orbit.point_from_proportion(self.t_offset % 1))

        def get_line_to_circle():
            return Line(origin_point, dot.get_center(), color=RED_A)

        def get_line_to_curve():
            x = self.curve_start[0] - self.t_offset * 4
            y = dot.get_center()[1]
            return Line(dot.get_center(), np.array([x,y,0]), color=YELLOW_A, stroke_width=2 )


        self.curve = VGroup()
        self.curve.add(Line(self.curve_start,self.curve_start))
        def get_curve():
            last_line = self.curve[-1]
            x = self.curve_start[0] - self.t_offset * 4
            y = dot.get_center()[1]
            new_line = Line(last_line.get_end(),np.array([x,y,0]), color=RED_D)
            self.curve.add(new_line)

            return self.curve

        dot.add_updater(go_around_circle)

        origin_to_circle_line = always_redraw(get_line_to_circle)
        dot_to_curve_line = always_redraw(get_line_to_curve)
        sine_curve_line = always_redraw(get_curve)

        
        self.add(dot)
        self.add(orbit, origin_to_circle_line, dot_to_curve_line, sine_curve_line)
        self.wait(8.5)

        dot.remove_updater(go_around_circle)

[04/11/23 19:18:38] INFO     Writing \pi to media/Tex/57b587a624f693b9.tex                   ]8;id=518585;file:///usr/local/lib/python3.9/dist-packages/manim/utils/tex_file_writing.py\tex_file_writing.py]8;;\:]8;id=515896;file:///usr/local/lib/python3.9/dist-packages/manim/utils/tex_file_writing.py#97\97]8;;\

INFO:manim:Writing \pi to media/Tex/57b587a624f693b9.tex


[04/11/23 19:18:39] INFO     Writing 2 \pi to media/Tex/e69f4b052f622ccf.tex                 ]8;id=865502;file:///usr/local/lib/python3.9/dist-packages/manim/utils/tex_file_writing.py\tex_file_writing.py]8;;\:]8;id=357798;file:///usr/local/lib/python3.9/dist-packages/manim/utils/tex_file_writing.py#97\97]8;;\

INFO:manim:Writing 2 \pi to media/Tex/e69f4b052f622ccf.tex


[04/11/23 19:18:40] INFO     Writing 3 \pi to media/Tex/cc5afe7220be0bed.tex                 ]8;id=794917;file:///usr/local/lib/python3.9/dist-packages/manim/utils/tex_file_writing.py\tex_file_writing.py]8;;\:]8;id=239406;file:///usr/local/lib/python3.9/dist-packages/manim/utils/tex_file_writing.py#97\97]8;;\

INFO:manim:Writing 3 \pi to media/Tex/cc5afe7220be0bed.tex


                    INFO     Writing 4 \pi to media/Tex/903915251f8e7d86.tex                 ]8;id=528240;file:///usr/local/lib/python3.9/dist-packages/manim/utils/tex_file_writing.py\tex_file_writing.py]8;;\:]8;id=182600;file:///usr/local/lib/python3.9/dist-packages/manim/utils/tex_file_writing.py#97\97]8;;\

INFO:manim:Writing 4 \pi to media/Tex/903915251f8e7d86.tex


[2. 0. 0.]


Waiting 0:   0%|          | 0/128 [00:00<?, ?it/s]

[2. 0. 0.]


Waiting 0:   2%|▏         | 2/128 [00:00<00:07, 16.42it/s]

[2.26666667 0.         0.        ]
[2.53333333 0.         0.        ]
[2.8 0.  0. ]
[3.06666667 0.         0.        ]
[3.33333333 0.         0.        ]
[3.6 0.  0. ]


Waiting 0:   6%|▋         | 8/128 [00:00<00:03, 36.83it/s]

[3.86666667 0.         0.        ]
[4.13333333 0.         0.        ]
[4.4 0.  0. ]
[4.66666667 0.         0.        ]


Waiting 0:  11%|█         | 14/128 [00:00<00:02, 43.59it/s]

[4.93333333 0.         0.        ]
[5.2 0.  0. ]
[5.46666667 0.         0.        ]
[5.73333333 0.         0.        ]
[6. 0. 0.]
[6.26666667 0.         0.        ]
[6.53333333 0.         0.        ]


Waiting 0:  15%|█▍        | 19/128 [00:00<00:02, 45.13it/s]

[6.8 0.  0. ]
[7.06666667 0.         0.        ]
[7.33333333 0.         0.        ]


Waiting 0:  19%|█▉        | 24/128 [00:00<00:02, 45.16it/s]

[7.6 0.  0. ]
[7.86666667 0.         0.        ]
[8.13333333 0.         0.        ]
[8.4 0.  0. ]
[8.66666667 0.         0.        ]
[8.93333333 0.         0.        ]


Waiting 0:  23%|██▎       | 29/128 [00:00<00:02, 44.33it/s]

[9.2 0.  0. ]
[9.46666667 0.         0.        ]
[9.73333333 0.         0.        ]


Waiting 0:  27%|██▋       | 34/128 [00:00<00:02, 43.51it/s]

[10.  0.  0.]
[10.26666667  0.          0.        ]
[10.53333333  0.          0.        ]
[10.8  0.   0. ]
[11.06666667  0.          0.        ]
[11.33333333  0.          0.        ]
[11.6  0.   0. ]
[11.86666667  0.          0.        ]
[12.13333333  0.          0.        ]


Waiting 0:  30%|███       | 39/128 [00:00<00:02, 42.42it/s]

[12.4  0.   0. ]
[12.66666667  0.          0.        ]
[12.93333333  0.          0.        ]
[13.2  0.   0. ]


Waiting 0:  34%|███▍      | 44/128 [00:01<00:02, 36.93it/s]

[13.46666667  0.          0.        ]
[13.73333333  0.          0.        ]
[14.  0.  0.]
[14.26666667  0.          0.        ]
[14.53333333  0.          0.        ]


Waiting 0:  38%|███▊      | 48/128 [00:01<00:02, 31.74it/s]

[14.8  0.   0. ]
[15.06666667  0.          0.        ]
[15.33333333  0.          0.        ]


Waiting 0:  41%|████      | 52/128 [00:01<00:02, 31.72it/s]

[15.6  0.   0. ]
[15.86666667  0.          0.        ]
[16.13333333  0.          0.        ]
[16.4  0.   0. ]


Waiting 0:  44%|████▍     | 56/128 [00:01<00:02, 31.60it/s]

[16.66666667  0.          0.        ]
[16.93333333  0.          0.        ]
[17.2  0.   0. ]


Waiting 0:  47%|████▋     | 60/128 [00:01<00:02, 30.54it/s]

[17.46666667  0.          0.        ]
[17.73333333  0.          0.        ]
[18.  0.  0.]
[18.26666667  0.          0.        ]
[18.53333333  0.          0.        ]
[18.8  0.   0. ]


Waiting 0:  50%|█████     | 64/128 [00:01<00:02, 29.90it/s]

[19.06666667  0.          0.        ]
[19.33333333  0.          0.        ]
[19.6  0.   0. ]
[19.86666667  0.          0.        ]

Waiting 0:  53%|█████▎    | 68/128 [00:01<00:02, 29.08it/s]


[20.13333333  0.          0.        ]
[20.4  0.   0. ]
[20.66666667  0.          0.        ]


Waiting 0:  55%|█████▌    | 71/128 [00:02<00:02, 28.31it/s]

[20.93333333  0.          0.        ]
[21.2  0.   0. ]


Waiting 0:  58%|█████▊    | 74/128 [00:02<00:01, 28.66it/s]

[21.46666667  0.          0.        ]
[21.73333333  0.          0.        ]
[22.  0.  0.]
[22.26666667  0.          0.        ]


Waiting 0:  60%|██████    | 77/128 [00:02<00:01, 27.94it/s]

[22.53333333  0.          0.        ]
[22.8  0.   0. ]


Waiting 0:  62%|██████▎   | 80/128 [00:02<00:01, 28.10it/s]

[23.06666667  0.          0.        ]
[23.33333333  0.          0.        ]
[23.6  0.   0. ]
[23.86666667  0.          0.        ]


Waiting 0:  66%|██████▌   | 84/128 [00:02<00:01, 28.40it/s]

[24.13333333  0.          0.        ]
[24.4  0.   0. ]


Waiting 0:  68%|██████▊   | 87/128 [00:02<00:01, 27.95it/s]

[24.66666667  0.          0.        ]
[24.93333333  0.          0.        ]
[25.2  0.   0. ]
[25.46666667  0.          0.        ]
[25.73333333  0.          0.        ]


Waiting 0:  70%|███████   | 90/128 [00:02<00:01, 27.76it/s]

[26.  0.  0.]


Waiting 0:  73%|███████▎  | 93/128 [00:02<00:01, 27.28it/s]

[26.26666667  0.          0.        ]
[26.53333333  0.          0.        ]
[26.8  0.   0. ]
[27.06666667  0.          0.        ]
[27.33333333  0.          0.        ]


Waiting 0:  75%|███████▌  | 96/128 [00:02<00:01, 27.26it/s]

[27.6  0.   0. ]


Waiting 0:  77%|███████▋  | 99/128 [00:03<00:01, 26.15it/s]

[27.86666667  0.          0.        ]
[28.13333333  0.          0.        ]
[28.4  0.   0. ]
[28.66666667  0.          0.        ]
[28.93333333  0.          0.        ]


Waiting 0:  80%|███████▉  | 102/128 [00:03<00:01, 25.87it/s]

[29.2  0.   0. ]


Waiting 0:  82%|████████▏ | 105/128 [00:03<00:00, 26.07it/s]

[29.46666667  0.          0.        ]
[29.73333333  0.          0.        ]
[30.  0.  0.]
[30.26666667  0.          0.        ]
[30.53333333  0.          0.        ]
[30.8  0.   0. ]
[31.06666667  0.          0.        ]


Waiting 0:  86%|████████▌ | 110/128 [00:03<00:00, 30.45it/s]

[31.33333333  0.          0.        ]


Waiting 0:  89%|████████▉ | 114/128 [00:03<00:00, 32.38it/s]

[31.6  0.   0. ]
[31.86666667  0.          0.        ]
[32.13333333  0.          0.        ]
[32.4  0.   0. ]
[32.66666667  0.          0.        ]
[32.93333333  0.          0.        ]
[33.2  0.   0. ]


Waiting 0:  92%|█████████▏| 118/128 [00:03<00:00, 33.71it/s]

[33.46666667  0.          0.        ]


Waiting 0:  95%|█████████▌| 122/128 [00:03<00:00, 34.96it/s]

[33.73333333  0.          0.        ]
[34.  0.  0.]
[34.26666667  0.          0.        ]
[34.53333333  0.          0.        ]
[34.8  0.   0. ]
[35.06666667  0.          0.        ]
[35.33333333  0.          0.        ]
[35.6  0.   0. ]


[35.86666667  0.          0.        ]
[35.86666667  0.          0.        ]


[04/11/23 19:18:45] INFO     Animation 0 : Partial movie file written in                   ]8;id=185174;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=269120;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py#527\527]8;;\
                             '/content/media/videos/content/480p15/partial_movie_files/Sin                         
                             eFunctionWithUnitCircle/4266129954_2101260726_2119512064.mp4'                         

INFO:manim:Animation 0 : Partial movie file written in '/content/media/videos/content/480p15/partial_movie_files/SineFunctionWithUnitCircle/4266129954_2101260726_2119512064.mp4'


[35.86666667  0.          0.        ]


Waiting 1:   0%|          | 0/15 [00:00<?, ?it/s]

[35.86666667  0.          0.        ]


Waiting 1:  13%|█▎        | 2/15 [00:00<00:00, 18.94it/s]

[36.13333333  0.          0.        ]
[36.4  0.   0. ]
[36.66666667  0.          0.        ]
[36.93333333  0.          0.        ]
[37.2  0.   0. ]
[37.46666667  0.          0.        ]


Waiting 1:  47%|████▋     | 7/15 [00:00<00:00, 33.81it/s]

[37.73333333  0.          0.        ]
[38.  0.  0.]
[38.26666667  0.          0.        ]
[38.53333333  0.          0.        ]


[38.8  0.   0. ]
[39.06666667  0.          0.        ]
[39.33333333  0.          0.        ]
[39.6  0.   0. ]
[39.6  0.   0. ]


[04/11/23 19:18:46] INFO     Animation 1 : Partial movie file written in                   ]8;id=406345;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=892279;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py#527\527]8;;\
                             '/content/media/videos/content/480p15/partial_movie_files/Sin                         
                             eFunctionWithUnitCircle/1442284246_3604166955_3760956451.mp4'                         

INFO:manim:Animation 1 : Partial movie file written in '/content/media/videos/content/480p15/partial_movie_files/SineFunctionWithUnitCircle/1442284246_3604166955_3760956451.mp4'


                    INFO     Combining to Movie file.                                      ]8;id=271987;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=968028;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py#617\617]8;;\

INFO:manim:Combining to Movie file.


                    INFO                                                                   ]8;id=176310;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=942035;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py#736\736]8;;\
                             File ready at                                                                         
                             '/content/media/videos/content/480p15/SineFunctionWithUnitCir                         
                             cle.mp4'                                                                              
                                                                                                                   

INFO:manim:
File ready at '/content/media/videos/content/480p15/SineFunctionWithUnitCircle.mp4'



                    INFO     Rendered SineFunctionWithUnitCircle                                       ]8;id=106742;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene.py\scene.py]8;;\:]8;id=263981;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene.py#241\241]8;;\
                             Played 2 animations                                                                   

INFO:manim:Rendered SineFunctionWithUnitCircle
Played 2 animations


In [4]:
%%manim -ql SineFunctionWithUnitCircle
from manim import *

class SineFunctionWithUnitCircle(Scene):
    # contributed by heejin_park, https://infograph.tistory.com/230
    def construct(self):
        self.show_axis()
        self.show_circle()
        self.move_dot_and_draw_curve()
        
        self.wait()

    def show_axis(self):
        x_start = np.array([-6,0,0])
        x_end = np.array([6,0,0])

        y_start = np.array([-4,-2,0])
        y_end = np.array([-4,2,0])

        x_axis = Line(x_start, x_end)
        y_axis = Line(y_start, y_end)

        self.add(x_axis, y_axis)
        self.add_x_labels()

        self.origin_point = np.array([-4,0,0])
        self.a=Dot().move_to(np.array([2,0,0]))
        def shift_right(obj, dt):
            obj.shift(RIGHT*2*dt)
            print(obj.get_center())  # print the coordinate of obj

        self.a.add_updater(shift_right)
        self.curve_start = self.a.get_center()
        print("point : ", self.curve_start)
        self.add(self.a)
        
        #np.array([3,0,0])

    def add_x_labels(self):
        x_labels = [
            MathTex("\pi"), MathTex("2 \pi"),
            MathTex("3 \pi"), MathTex("4 \pi"),
        ]

        for i in range(len(x_labels)):
            x_labels[i].next_to(np.array([-1 + 2*i, 0, 0]), DOWN)
            self.add(x_labels[i])

    def show_circle(self):
        circle = Circle(radius=1)
        circle.move_to(self.origin_point)
        self.add(circle)
        self.circle = circle

    def move_dot_and_draw_curve(self):
        orbit = self.circle
        origin_point = self.origin_point

        dot = Dot(radius=0.06, color=YELLOW)
        dot.move_to(orbit.point_from_proportion(0))
        self.t_offset = 0
        rate = 0.25

        def go_around_circle(mob, dt):
            self.t_offset += (dt * rate)
            # print(self.t_offset)
            mob.move_to(orbit.point_from_proportion(self.t_offset % 1))

        def get_line_to_circle():
            return Line(origin_point, dot.get_center(), color=RED_A)

        def get_line_to_curve():
            x = self.curve_start[0] - self.t_offset * 4
            y = dot.get_center()[1]
            return Line(dot.get_center(), np.array([x,y,0]), color=YELLOW_A, stroke_width=2 )


        self.curve = VGroup()
        self.curve.add(Line(self.curve_start,self.curve_start))
        def get_curve():
            last_line = self.curve[-1]
            x = self.curve_start[0] - self.t_offset * 4
            y = dot.get_center()[1]
            new_line = Line(last_line.get_end(),np.array([x,y,0]), color=RED_D)
            self.curve.add(new_line)

            return self.curve

        dot.add_updater(go_around_circle)

        origin_to_circle_line = always_redraw(get_line_to_circle)
        dot_to_curve_line = always_redraw(get_line_to_curve)
        sine_curve_line = always_redraw(get_curve)

        
        self.add(dot)
        self.add(orbit, origin_to_circle_line, dot_to_curve_line, sine_curve_line)
        self.wait(9.5)

        dot.remove_updater(go_around_circle)

point :  [2. 0. 0.]
[2. 0. 0.]


Waiting 0:   0%|          | 0/143 [00:00<?, ?it/s]

[2. 0. 0.]
[2.13333333 0.         0.        ]


Waiting 0:   1%|▏         | 2/143 [00:00<00:09, 15.56it/s]

[2.26666667 0.         0.        ]
[2.4 0.  0. ]
[2.53333333 0.         0.        ]
[2.66666667 0.         0.        ]
[2.8 0.  0. ]

Waiting 0:   6%|▌         | 8/143 [00:00<00:03, 36.59it/s]


[2.93333333 0.         0.        ]
[3.06666667 0.         0.        ]
[3.2 0.  0. ]
[3.33333333 0.         0.        ]
[3.46666667 0.         0.        ]
[3.6 0.  0. ]
[3.73333333 0.         0.        ]

Waiting 0:  10%|▉         | 14/143 [00:00<00:03, 42.38it/s]


[3.86666667 0.         0.        ]
[4. 0. 0.]
[4.13333333 0.         0.        ]


Waiting 0:  13%|█▎        | 19/143 [00:00<00:02, 43.26it/s]

[4.26666667 0.         0.        ]
[4.4 0.  0. ]
[4.53333333 0.         0.        ]
[4.66666667 0.         0.        ]
[4.8 0.  0. ]
[4.93333333 0.         0.        ]

Waiting 0:  17%|█▋        | 24/143 [00:00<00:02, 43.74it/s]


[5.06666667 0.         0.        ]
[5.2 0.  0. ]
[5.33333333 0.         0.        ]


Waiting 0:  20%|██        | 29/143 [00:00<00:02, 44.59it/s]

[5.46666667 0.         0.        ]
[5.6 0.  0. ]
[5.73333333 0.         0.        ]
[5.86666667 0.         0.        ]
[6. 0. 0.]
[6.13333333 0.         0.        ]


Waiting 0:  24%|██▍       | 34/143 [00:00<00:02, 42.34it/s]

[6.26666667 0.         0.        ]
[6.4 0.  0. ]
[6.53333333 0.         0.        ]


Waiting 0:  27%|██▋       | 39/143 [00:00<00:02, 41.87it/s]

[6.66666667 0.         0.        ]
[6.8 0.  0. ]
[6.93333333 0.         0.        ]
[7.06666667 0.         0.        ]
[7.2 0.  0. ]
[7.33333333 0.         0.        ]
[7.46666667 0.         0.        ]
[7.6 0.  0. ]


Waiting 0:  31%|███       | 44/143 [00:01<00:02, 37.59it/s]

[7.73333333 0.         0.        ]
[7.86666667 0.         0.        ]
[8. 0. 0.]
[8.13333333 0.         0.        ]


Waiting 0:  34%|███▎      | 48/143 [00:01<00:02, 34.19it/s]

[8.26666667 0.         0.        ]
[8.4 0.  0. ]


Waiting 0:  36%|███▋      | 52/143 [00:01<00:02, 32.58it/s]

[8.53333333 0.         0.        ]
[8.66666667 0.         0.        ]
[8.8 0.  0. ]
[8.93333333 0.         0.        ]
[9.06666667 0.         0.        ]
[9.2 0.  0. ]
[9.33333333 0.         0.        ]


Waiting 0:  39%|███▉      | 56/143 [00:01<00:02, 32.09it/s]

[9.46666667 0.         0.        ]
[9.6 0.  0. ]
[9.73333333 0.         0.        ]
[9.86666667 0.         0.        ]


Waiting 0:  42%|████▏     | 60/143 [00:01<00:02, 32.47it/s]

[10.  0.  0.]
[10.13333333  0.          0.        ]
[10.26666667  0.          0.        ]


Waiting 0:  45%|████▍     | 64/143 [00:01<00:02, 31.01it/s]

[10.4  0.   0. ]
[10.53333333  0.          0.        ]
[10.66666667  0.          0.        ]


Waiting 0:  48%|████▊     | 68/143 [00:01<00:02, 29.85it/s]

[10.8  0.   0. ]
[10.93333333  0.          0.        ]
[11.06666667  0.          0.        ]
[11.2  0.   0. ]
[11.33333333  0.          0.        ]
[11.46666667  0.          0.        ]


Waiting 0:  50%|█████     | 72/143 [00:02<00:02, 28.77it/s]

[11.6  0.   0. ]
[11.73333333  0.          0.        ]
[11.86666667  0.          0.        ]


Waiting 0:  52%|█████▏    | 75/143 [00:02<00:02, 28.50it/s]

[12.  0.  0.]
[12.13333333  0.          0.        ]
[12.26666667  0.          0.        ]


Waiting 0:  55%|█████▍    | 78/143 [00:02<00:02, 27.67it/s]

[12.4  0.   0. ]
[12.53333333  0.          0.        ]
[12.66666667  0.          0.        ]


Waiting 0:  57%|█████▋    | 81/143 [00:02<00:02, 27.43it/s]

[12.8  0.   0. ]
[12.93333333  0.          0.        ]
[13.06666667  0.          0.        ]


Waiting 0:  59%|█████▊    | 84/143 [00:02<00:02, 27.67it/s]

[13.2  0.   0. ]
[13.33333333  0.          0.        ]
[13.46666667  0.          0.        ]


Waiting 0:  61%|██████    | 87/143 [00:02<00:02, 26.59it/s]

[13.6  0.   0. ]
[13.73333333  0.          0.        ]
[13.86666667  0.          0.        ]


Waiting 0:  63%|██████▎   | 90/143 [00:02<00:01, 26.56it/s]

[14.  0.  0.]
[14.13333333  0.          0.        ]
[14.26666667  0.          0.        ]


Waiting 0:  65%|██████▌   | 93/143 [00:02<00:01, 26.51it/s]

[14.4  0.   0. ]
[14.53333333  0.          0.        ]
[14.66666667  0.          0.        ]


Waiting 0:  67%|██████▋   | 96/143 [00:02<00:01, 26.59it/s]

[14.8  0.   0. ]
[14.93333333  0.          0.        ]
[15.06666667  0.          0.        ]


Waiting 0:  69%|██████▉   | 99/143 [00:03<00:01, 26.09it/s]

[15.2  0.   0. ]
[15.33333333  0.          0.        ]
[15.46666667  0.          0.        ]


Waiting 0:  71%|███████▏  | 102/143 [00:03<00:01, 25.89it/s]

[15.6  0.   0. ]
[15.73333333  0.          0.        ]
[15.86666667  0.          0.        ]


Waiting 0:  73%|███████▎  | 105/143 [00:03<00:01, 25.54it/s]

[16.  0.  0.]
[16.13333333  0.          0.        ]
[16.26666667  0.          0.        ]


Waiting 0:  76%|███████▌  | 108/143 [00:03<00:01, 25.09it/s]

[16.4  0.   0. ]
[16.53333333  0.          0.        ]
[16.66666667  0.          0.        ]


Waiting 0:  78%|███████▊  | 111/143 [00:03<00:01, 24.94it/s]

[16.8  0.   0. ]
[16.93333333  0.          0.        ]
[17.06666667  0.          0.        ]


Waiting 0:  80%|███████▉  | 114/143 [00:03<00:01, 24.57it/s]

[17.2  0.   0. ]


Waiting 0:  82%|████████▏ | 117/143 [00:03<00:01, 23.29it/s]

[17.33333333  0.          0.        ]
[17.46666667  0.          0.        ]
[17.6  0.   0. ]
[17.73333333  0.          0.        ]
[17.86666667  0.          0.        ]


Waiting 0:  86%|████████▌ | 123/143 [00:04<00:00, 23.37it/s]

[18.  0.  0.]
[18.13333333  0.          0.        ]
[18.26666667  0.          0.        ]
[18.4  0.   0. ]
[18.53333333  0.          0.        ]
[18.66666667  0.          0.        ]


Waiting 0:  88%|████████▊ | 126/143 [00:04<00:00, 23.78it/s]

[18.8  0.   0. ]
[18.93333333  0.          0.        ]
[19.06666667  0.          0.        ]


Waiting 0:  90%|█████████ | 129/143 [00:04<00:00, 24.13it/s]

[19.2  0.   0. ]
[19.33333333  0.          0.        ]
[19.46666667  0.          0.        ]


Waiting 0:  92%|█████████▏| 132/143 [00:04<00:00, 24.03it/s]

[19.6  0.   0. ]
[19.73333333  0.          0.        ]


Waiting 0:  94%|█████████▍| 135/143 [00:04<00:00, 22.51it/s]

[19.86666667  0.          0.        ]
[20.  0.  0.]
[20.13333333  0.          0.        ]


Waiting 0:  97%|█████████▋| 138/143 [00:04<00:00, 22.04it/s]

[20.26666667  0.          0.        ]
[20.4  0.   0. ]


Waiting 0:  99%|█████████▊| 141/143 [00:04<00:00, 22.18it/s]

[20.53333333  0.          0.        ]
[20.66666667  0.          0.        ]
[20.8  0.   0. ]


[20.93333333  0.          0.        ]
[20.93333333  0.          0.        ]


[04/11/23 19:22:09] INFO     Animation 0 : Partial movie file written in                   ]8;id=439964;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=400920;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py#527\527]8;;\
                             '/content/media/videos/content/480p15/partial_movie_files/Sin                         
                             eFunctionWithUnitCircle/4266129954_1865452027_3764689128.mp4'                         

INFO:manim:Animation 0 : Partial movie file written in '/content/media/videos/content/480p15/partial_movie_files/SineFunctionWithUnitCircle/4266129954_1865452027_3764689128.mp4'


[20.93333333  0.          0.        ]


Waiting 1:  20%|██        | 3/15 [00:00<00:00, 29.42it/s]

[20.93333333  0.          0.        ]
[21.06666667  0.          0.        ]
[21.2  0.   0. ]
[21.33333333  0.          0.        ]
[21.46666667  0.          0.        ]
[21.6  0.   0. ]
[21.73333333  0.          0.        ]
[21.86666667  0.          0.        ]


[22.  0.  0.]
[22.13333333  0.          0.        ]
[22.26666667  0.          0.        ]
[22.4  0.   0. ]
[22.53333333  0.          0.        ]
[22.66666667  0.          0.        ]
[22.8  0.   0. ]
[22.8  0.   0. ]


                    INFO     Animation 1 : Partial movie file written in                   ]8;id=26499;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=387586;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py#527\527]8;;\
                             '/content/media/videos/content/480p15/partial_movie_files/Sin                         
                             eFunctionWithUnitCircle/1442284246_3604166955_1763887070.mp4'                         

INFO:manim:Animation 1 : Partial movie file written in '/content/media/videos/content/480p15/partial_movie_files/SineFunctionWithUnitCircle/1442284246_3604166955_1763887070.mp4'


                    INFO     Combining to Movie file.                                      ]8;id=504649;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=39104;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py#617\617]8;;\

INFO:manim:Combining to Movie file.


                    INFO                                                                   ]8;id=724079;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py\scene_file_writer.py]8;;\:]8;id=23383;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene_file_writer.py#736\736]8;;\
                             File ready at                                                                         
                             '/content/media/videos/content/480p15/SineFunctionWithUnitCir                         
                             cle.mp4'                                                                              
                                                                                                                   

INFO:manim:
File ready at '/content/media/videos/content/480p15/SineFunctionWithUnitCircle.mp4'



                    INFO     Rendered SineFunctionWithUnitCircle                                       ]8;id=570576;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene.py\scene.py]8;;\:]8;id=370419;file:///usr/local/lib/python3.9/dist-packages/manim/scene/scene.py#241\241]8;;\
                             Played 2 animations                                                                   

INFO:manim:Rendered SineFunctionWithUnitCircle
Played 2 animations
